# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Safin's Fastpages Site
description: Hi! This is my fastpages site built for APCSP.
github_username: safinsingh
github_repo: "fastpages-apcsp"

url: "https://safinsingh.github.io" 
baseurl: "/fastpages-apcsp"

use_math: true
show_description: true
show_image: false
annotations: false
show_tags: true

google_analytics: UA-153511540-4

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

include:
  - _pages

default_badges:
  github: true
  binder: true
  colab: true
  deepnote: true

# Escape HTML in post descriptions
html_escape:
  description: false

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# to limit size of xml as it can grow quite large.
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
  
exclude:
  - settings.ini
